# Generated by Django 3.0.7 on 2020-07-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=15, null=True)),
                ('src', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=3, null=True)),
                ('index', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classroom', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('build', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.CharField(blank=True, max_length=5, null=True)),
                ('class1_2', models.BooleanField(default=False)),
                ('class3_4', models.BooleanField(default=False)),
                ('class5_6', models.BooleanField(default=False)),
                ('class7_8', models.BooleanField(default=False)),
                ('class9_11', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('real_time_number', models.IntegerField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('service', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceNumber',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('real_time_number', models.IntegerField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('administrators', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('name1', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('student_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=15, null=True)),
                ('authority', models.CharField(blank=True, default=1, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=5, null=True)),
                ('classes', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('academy', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(blank=True, max_length=10, null=True)),
                ('school', models.CharField(blank=True, max_length=15, null=True)),
                ('src', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolHospitalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(blank=True, max_length=15, null=True)),
                ('time', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('version', models.CharField(blank=True, max_length=4, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('release_time', models.DateField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.ForeignKey(db_column='publisher', on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNotify',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False, unique=True)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('release_time', models.DateField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.ForeignKey(db_column='publisher', on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.User')),
            ],
        ),
    ]
