# Generated by Django 3.0.7 on 2020-07-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolhospitalappointment',
            name='version',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
