# Generated by Django 3.0.7 on 2020-07-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_schoolhospitalappointment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='placenumber',
            name='administrators',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='placeinfo',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
