# Generated by Django 3.0.7 on 2020-07-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200711_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placenumber',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
