# Generated by Django 3.0.7 on 2020-07-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20200715_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
