# Generated by Django 3.0.7 on 2020-07-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20200714_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolhospitalappointment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.User'),
        ),
    ]
