# Generated by Django 3.0.7 on 2020-07-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20200716_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='src',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
