# Generated by Django 3.0.7 on 2020-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20200714_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='build_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('src', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=3, null=True)),
                ('index', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
