# Generated by Django 3.0.7 on 2020-07-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200716_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'API',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CloudVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=50)),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('href', models.TextField()),
                ('size', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cloud Videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'detector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('mid', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('name', models.TextField()),
                ('size', models.FloatField()),
                ('details', models.TextField()),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('mid', models.CharField(blank=True, max_length=50, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Monitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=50, null=True)),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('shto', models.TextField(blank=True, null=True)),
                ('shfr', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('ext', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('fps', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=15, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('stoptime', models.CharField(max_length=20)),
                ('starttime', models.CharField(max_length=20)),
                ('enable', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Monitors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Presets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('start', models.CharField(blank=True, max_length=10, null=True)),
                ('end', models.CharField(blank=True, max_length=10, null=True)),
                ('enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'Schedules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimelapseFrames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'Timelapse Frames',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timelapses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'Timelapses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('auth', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('pass_field', models.CharField(blank=True, db_column='pass', max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=50, null=True)),
                ('ke', models.CharField(blank=True, max_length=50, null=True)),
                ('ext', models.CharField(blank=True, max_length=4, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('frames', models.IntegerField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Videos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.AlterModelOptions(
            name='buildinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='classroomnumber',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='latestnotify',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='placeinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='placenumber',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='schoolhospitalappointment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
