# Generated by Django 3.0.7 on 2020-07-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_build_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build_info',
            name='src',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
