# Generated by Django 3.0.7 on 2020-07-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20200716_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolhospitalappointment',
            name='symptom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
