# Generated by Django 3.0.7 on 2020-07-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20200718_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream_of_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('max_number', models.IntegerField(blank=True, null=True)),
                ('max_stage', models.IntegerField(blank=True, null=True)),
                ('six', models.IntegerField(blank=True, default=0, null=True)),
                ('seven', models.IntegerField(blank=True, default=0, null=True)),
                ('eight', models.IntegerField(blank=True, default=0, null=True)),
                ('nine', models.IntegerField(blank=True, default=0, null=True)),
                ('ten', models.IntegerField(blank=True, default=0, null=True)),
                ('eleven', models.IntegerField(blank=True, default=0, null=True)),
                ('twelve', models.IntegerField(blank=True, default=0, null=True)),
                ('thirteen', models.IntegerField(blank=True, default=0, null=True)),
                ('fourteen', models.IntegerField(blank=True, default=0, null=True)),
                ('fifteen', models.IntegerField(blank=True, default=0, null=True)),
                ('sixteen', models.IntegerField(blank=True, default=0, null=True)),
                ('seventeen', models.IntegerField(blank=True, default=0, null=True)),
                ('eighteen', models.IntegerField(blank=True, default=0, null=True)),
                ('nineteen', models.IntegerField(blank=True, default=0, null=True)),
                ('twenty', models.IntegerField(blank=True, default=0, null=True)),
                ('twenty_one', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
