# Generated by Django 3.0.7 on 2020-07-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_stream_of_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream_of_people',
            name='eight',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='eighteen',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='fourteen',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='six',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='sixteen',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='twelve',
        ),
        migrations.RemoveField(
            model_name='stream_of_people',
            name='twenty',
        ),
        migrations.AddField(
            model_name='stream_of_people',
            name='real_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
