# Generated by Django 3.0.7 on 2020-07-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_auto_20200715_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('real_time_number', models.IntegerField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
