# Generated by Django 3.0.7 on 2020-07-15 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_class_room'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='build_info',
            new_name='BuildInfo',
        ),
        migrations.RenameModel(
            old_name='class_room',
            new_name='ClassroomNumber',
        ),
    ]
