# Generated by Django 3.0.7 on 2020-07-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_stream_of_people_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('place', models.CharField(blank=True, max_length=10, null=True)),
                ('real_time_number', models.IntegerField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('administrators', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
