# Generated by Django 3.0.7 on 2020-07-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temp',
            old_name='max_people',
            new_name='is_delete',
        ),
        migrations.RemoveField(
            model_name='temp',
            name='state',
        ),
    ]
