# Generated by Django 3.0.4 on 2020-08-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_user_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_path',
            name='name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user_path',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
