# Generated by Django 3.0.4 on 2020-08-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_auto_20200817_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_path',
            new_name='UserPath',
        ),
    ]
