# Generated by Django 3.0.4 on 2020-08-20 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_remove_userpath_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpath',
            old_name='x',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='userpath',
            old_name='y',
            new_name='lng',
        ),
    ]
