# Generated by Django 3.0.4 on 2020-08-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_auto_20200820_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
