# Generated by Django 3.0.4 on 2020-10-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpath',
            name='generateKey',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
