# Generated by Django 3.0.4 on 2020-10-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_userpath_generatekey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpath',
            old_name='generateKey',
            new_name='publicKey',
        ),
    ]
