# Generated by Django 3.0.4 on 2020-10-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_auto_20201020_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='lat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='lng',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='publicKey',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
