# Generated by Django 3.0.4 on 2020-10-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_auto_20201020_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomnumber',
            name='administrators',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
