# Generated by Django 3.0.4 on 2020-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_classroomnumber_administrators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpath',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userpath',
            name='lng',
            field=models.FloatField(),
        ),
    ]
